pub mod injection;
pub mod transcription;
pub mod audio_capture;
pub mod server;
pub mod tailscale;
pub mod llm;
pub mod model_manager;
pub mod word_bank;
pub mod history;
pub mod templates;
pub mod tts;
pub mod gpu_guard;
#[cfg(feature = "gpu")]
pub mod gpu_detect;
pub mod power_events;
